### ISSUE TITLE
Newbie Question: Providing the connection settings during run-time?

### ISSUE THREAD

**Issue by bradws** [voryx/angular-wamp#11]
Awesome framework. Working well with C# backend Wampsharp.

Anyway, the docs specify providing the Router&Realm literal constants in the 'angular.config(..)'.

I'm wanting to provide these at RUN-TIME (posssibly as constants, not literal strings). I'm openning the connection at 'angular.run(...)' as per the docs, but how do I provide the connection settings after all the angular modules have been loaded? I've played around with '$wamp.connection' but couldn't get it working. (I'm a bit new to angular anyway)

Does the connection settings *have* to be provided in angular.config(..) ?
Cheers.

**Comment by davidwdan** [comment]
Thank you.  I'm glad it's working well with C#.

You can create a new service that wraps the $wampProvider and configure it at that point.  Something like this:

```JS
    .provider('$wamp2', function ($wampProvider) {
        var options = {
            url: 'ws://localhost:9090/',
            realm: 'realm1'
        };
        this.$get = function ($rootScope, $q, $log) {
            var wp = $wampProvider;
            wp.init(options);
            return wp.$get($rootScope, $q, $log);
        };
    })
```
After that, you'll use ``$wamp2`` throughout your project instead of ``$wamp``

Also, you can open the connection from any service or controller that ``$wamp`` can be injected in to, it doesn't only have to be opened in .run().

Let me know if that if that's the answer you're looking for.

**Comment by deceze** [comment]
I have the same issue. I want to use WAMP-CRA authentication with *user provided credentials*. The problem is I'd need to pass those to `$wampProvider.init` from the controller, but in the controller I have no access to `$wampProvider`, and in the places where I do have access to `$wampProvider` I don't know the user credentials yet. It's quite a catch-22 and it needs a lot of bending over backwards to solve this. Some nicer API would be appreciated here. In the end, I'd want:

    .controller('Foo', function ($scope, $wamp) {
        $scope.login = function (user) {
            $wamp.setOptions({ authid: user.name });
            $scope.$on('$wamp.onchallenge', function (e, data) {
                return data.promise.resolve(password);
            });
            $wamp.open();
        };
    })

**Comment by davidwdan** [comment]
@deceze 

I've added support for this, but you'll need to grab the current dev master.

```JS

  .controller('Foo', function ($scope, $wamp) {
       $scope.login = function() { 
           $wamp.setAuthId($scope.user.name, true); //Sets the authid and opens the connection
           $scope.$on('$wamp.onchallenge', function (e, data) {
                return data.promise.resolve(password);
           });
       };
  })

```

**Comment by deceze** [comment]
Thanks. :) Have you pushed this change yet?

**Comment by davidwdan** [comment]
@deceze yes, it has been pushed up:  https://github.com/voryx/angular-wamp/blob/master/src/angular-wamp.js#L269

**Comment by deceze** [comment]
@davidwdan Thanks, works well.
