### ISSUE TITLE
Multiple servers

### ISSUE THREAD

**Issue by devfxplayer** [voryx/angular-wamp#38]
Hi I have multiple server which have different IPs and ports.
I would like to connect to all of them from the same angular client.
Is that possible?

**Comment by mbonneau** [comment]
Please see #9 .

**Comment by devfxplayer** [comment]
Hi, this is not the same.
I have multiple connections on different servers not the same server as in that post.

**Comment by creat-or** [comment]
+1

**Comment by creat-or** [comment]
Maybe you can help me with a related issue:
I need to connect to one host. If it fails (with `unreachable`), I want to open _another_ connection to another host. Problems are that I have to

1. open a second connection
1. don't know the IP of the second connection on startup time, because the user has to select one of many.

Is this possible with the current $wamp implementation?

Thank you!

**Comment by davidwdan** [comment]
Multiple connections is now supported in v0.2.1
